apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadfkqa3200-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadfkqa3200-tenant-component
    app.kubernetes.io/part-of: loadfkqa3200-tenant-app
  name: loadfkqa3200-tenant-component
  namespace: loadfkqa3200-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: loadfkqa3200-tenant-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: loadfkqa3200-tenant-component
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:aef657d98c644ac59a65eba2036c897f
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
